name: Keep Render Alive

on:
  schedule:
    - cron: "*/14 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          curl -s "https://orders-km0s.onrender.com/" > /dev/null
